language: java
jdk:
    - openjdk11

branches:
    only:
        - develop

script: "cd /home/jparangdev/workspace/challenge-bird/api-server\ 
         git pull"

notifications:
    slack: 32devs:PFwYRPBzxGeJivhSFtMdMhVw