version: "3.7"

services:
    api-server:
        build: .
        ports:
            - "20002:8080"
        container_name: challenge-bird-api
        depends_on:
            -   db
        environment:
            SPRING_PROFILES_ACTIVE: local
            SPRING_DATASOURCE_URL: jdbc:log4jdbc:mariadb://db:3306/bird?useSSL=false
            SPRING_DATASOURCE_USERNAME: bird-dev
            SPRING_DATASOURCE_PASSWORD: devv
        links:
            -   db
    db:
        image: mariadb
        volumes:
            -   "~/DB/challenge-bird-db/data:/var/bin/mysql"
            -   "~/DB/challenge-bird-db/init:/docker-entrypoint-initdb.d"
            -   "~/DB/challenge-bird-db/conf:/etc/mysql"
        restart: always
        ports:
            -   "20001:3306"
        container_name: challenge-bird-db
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: 32dev
            MYSQL_DATABASE: bird
            MYSQL_USER: bird-dev
            MYSQL_PASSWORD: devv