spring:
    config:
        activate:
            on-profile: dev-db
    datasource:
        url: jdbc:log4jdbc:mariadb://db:3306/bird?useSSL=false
        username: bird-dev
        password: devv
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: false

