spring:
    config:
        activate:
            on-profile: local-db
    datasource:
        url: jdbc:log4jdbc:mariadb://127.0.0.1:20001/bird?useSSL=false&characterEncoding=UTF-8&autoReconnect=true
        username: bird-dev
        password: devv
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: false

