spring:
    config:
        activate:
            on-profile: local-db
    datasource:
        url: jdbc:log4jdbc:mariadb://127.0.0.1:20001/bird?c
        username: bird-dev
        password: ddev
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jpa:
        hibernate:
            ddl-auto: update
